name: cleavage_benchmark
channels:
  - huggingface
  - pytorch
  - conda-forge
  - fastchan
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - huggingface_hub=0.9.0
  - numpy=1.22.3
  - pip=21.2.4
  - python=3.10.8
  - pytorch=1.11.0
  - scikit-learn
  - scipy=1.7.3
  - tokenizers=0.10.3
  - torchtext=0.12.0
  - pip:
      - fair-esm==1.0.0
      - fairscale==0.4.8
      - huggingface-hub==0.9.0
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.2
      - ray==1.13.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.96
      - spacy-legacy==3.0.9
      - spacy-loggers==1.0.2
      - torchdata==0.3.0a0+1546ecf
      - torchsummary==1.5.1
      - tqdm==4.64.1
      - transformers==4.15.0
